### ISSUE TITLE
SSH, vim, and zsh

### ISSUE THREAD

**Issue by SolarAquarion** [dotphiles/dotphiles#9]
How do I save my ssh/gpg keys with the symlinking and stuff.  Also can I use oh my zsh with the zsh dotfiles?  Vim is just getting solarized and stuff?

**Comment by benohara** [comment]
I specifically ignore private keys..dont add them to your repo.

ssh key for example is only needed on your 'local' machine, use agent forwarding to pass it around.

gpg - no idea, i only use it locally.

From this repo, you should be able to drop anything in (whether is works or not I dont know), but should be able to replace dotzsh with oh-my-zsh.

Yeah, vims just base16 and a load of plugins

**Comment by bardo** [comment]
@benohara Agree, for gpg is the same reasoning as for ssh: don't commit them to a public repo.

I think this issue can be closed :)

**Comment by benohara** [comment]
@bardo agreed, closing
